services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    restart: unless-stopped
    command: /bin/bash -c "cd /usr/src/app;rm -rf * .*;git clone https://$API_KEY@github.com/$repo .;pip install --no-cache-dir -r requirements.txt;python ./main.py"
