version: '3.5'
services:
  python:
    build:
      container_name: python-git-ffmpeg
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    command: git clone https://{$API_KEY}@github.com/{$repo} .;pip install --no-cache-dir -r requirements.txt;python ./main.py